# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCodelesssample():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_codelesssample(self):
    self.driver.get("http://selenium1py.pythonanywhere.com/en-gb/")
    self.driver.set_window_size(1807, 811)
    self.driver.find_element(By.ID, "login_link").click()
    self.driver.find_element(By.ID, "id_registration-email").click()
    self.driver.find_element(By.ID, "id_registration-email").send_keys("maddluxx@gmail.com")
    self.driver.find_element(By.ID, "id_registration-password1").click()
    self.driver.find_element(By.ID, "id_registration-password1").send_keys("G3VHZfqfB3UKiAy")
    self.driver.find_element(By.ID, "id_registration-password2").send_keys("G3VHZfqfB3UKiAy")
    self.driver.find_element(By.NAME, "registration_submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alertinner").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".alertinner")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".page > .page_inner > .row").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alertinner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alertinner").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".alertinner")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".alert").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alertinner").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".alertinner").text == "Thanks for registering!"
  
